### PR TITLE
fix: Improve view for smaller screens

### LINKED ISSUE #3: Add software version indication
In the app it should be clear at what version of software we are looking at. The software version should cover frontend, backend and the default templates pack

### PR DESCRIPTION
**Pull request by freshavocado7**
Adjustment Have been made to both HomeView and TemplatesView here are some the changes:

- HomeView view fixed for smaller screens
- TemplatesView fixed for smaller screens
- InstanceView gained more space when in smaller screens
- Select Instance text position fixed
- If Select Instance is visible on the screen and User is currently in a small window the sidebar will automatically expand 
- New button for navigating back to the Home Screen
- New button appears on the Header for collapsing and expanding the sidebar
- On smaller screen the Title text of the header gets hidden and truncated for the main label title
- Label title can be viewed in full if hovered
- Print button is not visible anymore on smaller screens

closes: #7 

After merging the add-software-version branch this PR also closes #3  
Some minor UI changes were done in order to implement the software version display

### CODE REVIEW

File: frontend/src/components/InstanceView.jsx [hunk 1]
```diff
@@ -59,47 +59,51 @@ export const InstanceView = ({ templateName, objectID, endpoint }) => {
...
+                key={idx}
+                dangerouslySetInnerHTML={{
+                  __html: item.content,
+                }}
+              />
+            );
+          }
+        })}
+      </div>
+      <div className="mb-8 mt-8 text-center 3xl:hidden">
```
Comment (MoritzWeber0) [inline frontend/src/components/InstanceView.jsx:104]: Since the SoftwareVersion appears in all components, I'd rather move it the App.jsx. It has the advantage that it only has to be included once.

File: frontend/src/components/SoftwareVersion.jsx [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+import React, { useState, useEffect } from "react";
+import { API_BASE_URL, ROUTE_PREFIX } from "../APIConfig";
+
+export const SoftwareVersion = () => {
+  const [frontendVersion, setFrontendVersion] = useState(null);
+  const [backendVersion, setBackendVersion] = useState(null);
+
+  useEffect(() => {
+    fetch(`${ROUTE_PREFIX}/static/version.json`)
+      // fetch("/static/version.json")
```
Comment (MoritzWeber0) [inline frontend/src/components/SoftwareVersion.jsx:13]:
```suggestion
```

Remove unused comments.

File: frontend/src/components/SoftwareVersion.jsx [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+      .catch((error) => {
+        console.error(error);
+        setBackendVersion("Fetch failed");
+      });
+  }, []);
+
+  return (
+    <div className="text-gray-500 dark:text-gray-300">
+      {frontendVersion && (
+        <div className="version-info">
```
Comment (MoritzWeber0) [inline frontend/src/components/SoftwareVersion.jsx:35]:
```suggestion
        <div>
```

I can't find the declaration for the version-info class.

File: frontend/src/components/SoftwareVersion.jsx [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+          Frontend Version: {frontendVersion.version}
+        </div>
+      )}
+      {backendVersion && (
+        <div className="version-info">Backend Version: {backendVersion}</div>
```
Comment (MoritzWeber0) [inline frontend/src/components/SoftwareVersion.jsx:40]:
```suggestion
        <div>Backend Version: {backendVersion}</div>
```

I can't find the declaration for the version-info class.

File: frontend/src/components/ViewsList.jsx [hunk 5]
```diff
@@ -20,12 +20,12 @@ export const ViewsList = ({ templates, cardClickCallback }) => {
         if (cat in templates && templates[cat].length > 0) {
           return (
             <div key={cat} className="mb-8 p-4  ">
-              <h2 className="border-b border-gray-900 pb-2 text-2xl font-bold dark:border-gray-300">
+              <h2 className="border-b border-gray-900 pb-2 text-2xl  font-bold dark:border-gray-300">
```
Comment (MoritzWeber0) [inline frontend/src/components/ViewsList.jsx:23]:
```suggestion
              <h2 className="border-b border-gray-900 pb-2 text-2xl font-bold dark:border-gray-300">
```

Make sure that your prettier (+ Tailwind extension) is properly set up. This should handle those cases already.

File: frontend/src/components/ViewsList.jsx [hunk 6]
```diff
@@ -20,12 +20,12 @@ export const ViewsList = ({ templates, cardClickCallback }) => {
...
                 <span className=" px-4 py-2 text-gray-900 dark:text-gray-100">
                   {categories[cat]}
                 </span>
               </h2>
-              <div className="mt-2 flex flex-wrap justify-center gap-y-2">
+              <div className="mt-2 grid grid-cols-1 gap-4 md:flex md:flex-wrap md:justify-center ">
```
Comment (MoritzWeber0) [inline frontend/src/components/ViewsList.jsx:28]: What exactly is the benefit of having a grid with one column?

Comment (MoritzWeber0) [inline frontend/src/components/ViewsList.jsx:28]:
```suggestion
              <div className="mt-2 block gap-4 md:flex md:flex-wrap md:justify-center">
```

What exactly is the benefit of having a grid with one column despite having the gap feature? Instead, I'd use block and ignore the gap (gap between template cards is already covered by margin).

File: frontend/src/views/TemplateView.jsx [hunk 7]
```diff
@@ -35,29 +36,34 @@ export const TemplateView = ({ endpoint }) => {
...
+    }
+  }, [objectID, singleObjectID]);
   return (
     <div>
       <Header />
       {isSmallScreen && (
         <button
           onClick={toggleSidebar}
-          className={`fixed left-1/2 top-16 z-20 m-4 flex h-10 w-auto -translate-x-1/2 transform cursor-pointer items-center justify-center rounded-full bg-blue-500 p-2 px-4 text-sm text-white transition-transform duration-500 ease-in-out hover:bg-blue-700 focus:outline-none`}
+          className={`text-md fixed left-1/2 top-16 z-20 m-4 flex h-10 w-auto -translate-x-1/2 cursor-pointer items-center justify-center rounded-b-md border-2 border-gray-900 bg-custom-blue p-2 px-4 text-white transition-transform duration-500 ease-in-out hover:bg-custom-blue-hover focus:outline-none dark:border-white`}
```
Comment (MoritzWeber0) [inline frontend/src/views/TemplateView.jsx:55]: Also here, I'd split the classes into multiple lines.

File: frontend/src/views/TemplateView.jsx [hunk 8]
```diff
@@ -35,29 +36,34 @@ export const TemplateView = ({ endpoint }) => {
...
       <div className="flex">
         <div
-          className={`z-19 mt-20 flex w-96 transform flex-col items-center transition-all duration-700 ease-in-out ${
-            isSidebarVisible ? "translate-y-0 " : "hidden"
+          className={`z-19 mt-32 flex min-w-80 transform flex-col items-center md:mr-8 md:mt-20 ${
+            isSidebarVisible ? "mr-8 translate-y-0" : "hidden"
           }`}
         >
-          <aside className="h-auto min-w-80 flex-col overflow-y-auto rounded-lg shadow-lg dark:shadow-dark print:hidden">
+          <aside className="h-auto  flex-col overflow-y-auto rounded-lg shadow-lg dark:shadow-dark print:hidden">
```
Comment (MoritzWeber0) [inline frontend/src/views/TemplateView.jsx:66]:
```suggestion
          <aside className="h-auto flex-col overflow-y-auto rounded-lg shadow-lg dark:shadow-dark print:hidden">
```

File: frontend/src/views/TemplateView.jsx [hunk 9]
```diff
@@ -66,16 +72,18 @@ export const TemplateView = ({ endpoint }) => {
...
-            <div className="relative ml-12 mr-12 flex flex-1 ">
-              <div className="html-wrapper relative flex h-screen items-center justify-center pt-28">
-                {!!!objectID && !!!singleObjectID && (
-                  <p
-                    className={`${isSmallScreen ? "ml-32" : "ml-80"} text-xl text-gray-700 dark:text-gray-300 `}
-                  >
-                    Select an Instance
-                  </p>
-                )}
+          <div className="overflow-y-auto md:w-[100vw]">
```
Comment (MoritzWeber0) [inline frontend/src/views/TemplateView.jsx:75]:
```suggestion
          <div className="overflow-y-auto md:w-screen">
```

File: frontend/src/views/TemplateView.jsx [hunk 10]
```diff
@@ -66,16 +72,18 @@ export const TemplateView = ({ endpoint }) => {
...
+            {!!!objectID && !!!singleObjectID && (
```
Comment (MoritzWeber0) [inline frontend/src/views/TemplateView.jsx:76]:
```suggestion
            {!objectID && !singleObjectID && (
```

In this case, triple exclamation marks should be exactly the same.

File: frontend/src/views/TemplateView.jsx [hunk 11]
```diff
@@ -66,16 +72,18 @@ export const TemplateView = ({ endpoint }) => {
...
+              <p
+                className={`absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 transform text-xl text-gray-700 dark:text-gray-300 ${
+                  isSidebarVisible && isSmallScreen ? "hidden" : ""
+                }`}
```
Comment (MoritzWeber0) [inline frontend/src/views/TemplateView.jsx:80]:
```suggestion
                className={
                  "absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 transform text-xl text-gray-700 dark:text-gray-300" +
                  (isSidebarVisible && isSmallScreen ? "hidden" : "")
                }
```

**Review by MoritzWeber0 — COMMENTED** [review]
Really appreciate the many minor changes, thanks! Functional tests look good so far (some minor issues, but I've added comments for those), also the Collaboration Manager integration still works. 

I have a bunch of comments, some related to formatting, others related to consistency in the project. Some comments are unrelated to the PR, but nonetheless I wrote them down. It's your decision how you handle them. Regarding the main change, I'd move the SoftwareVersion embedding to the App component since it should be visible for all parts of the application.

File: frontend/src/components/InstanceView.jsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (freshavocado7) [reply frontend/src/components/InstanceView.jsx:104]: This is related to the hacky/dumb approach i mentioned in the daily the other day.
Currently im displaying the version on the bottom left corner in the TemplateView when on bigger screens.
When an InstanceView is loaded the pages height changes dynamically which therefore makes it hard for me to place the version at the middle and bottom (underneath) the instance from within TemplateView. That why i also load in in InstanceView since i have easy access to the Height of the page. 

I'm Open for suggestions 😄
